//=================================================================================================//
// filename: VTFLoaderPlugIn.h                                                          //
//                                                                                                 //
//           ATI Research, Inc.                                                                    //
//           3D Application Research Group                                                         //
//                                                                                                 //
// description: TexturePlugIn template file generated by Wizard                                   //
//                                                                                                 //
//=================================================================================================//
//   (C) 2004 ATI Research, Inc.  All rights reserved.                                             //
//=================================================================================================//

#ifndef _VTFLoader_PlugIn_H_
#define _VTFLoader_PlugIn_H_

// Forward declaration:
class CVTFLoaderPlugIn;

//..............................................................................................................//
//..............................................................................................................//
//..............................................................................................................//
//
// Texture loader class declaration. This particular Texture loader's purpose is to load the DirectX X meshes
// into RenderMonkey's model data files. See SDK/Include/Core/IRmPlugIn.h for definition of 
// IRmTextureLoaderPlugIn
//
//..............................................................................................................//
//..............................................................................................................//
//..............................................................................................................//
class CVTFLoaderPlugIn : public IRmTextureLoaderPlugIn
{
public :
   CVTFLoaderPlugIn();
   virtual ~CVTFLoaderPlugIn();

   //..............................................................................................
   // Methods below are inherited from IRmTextureLoaderPlugIn
   //..............................................................................................

   //---------------------------------------------------------------------------------
   // This method returns a list of file extensions that are supported by this Texture
   // loader plug-in for importing Texture from. These values are used to control the
   // display of files in the FileOpen dialog for model load. Note that number of entries
   // for 'formatDescriptions' and 'formatExtensions' must match.
   //
   // Eg. For X file, extension = "*.BMP"
   //                 text      = "BMP File (*.BMP)"
   //
   //---------------------------------------------------------------------------------
   virtual void GetSupportedExtensions( RmTextureType textureType,
                                        RmLinkedList<RmStringT> &formatDescriptions,
                                        RmLinkedList<RmStringT> &formatExtensions );

   //---------------------------------------------------------------------------------
   // Method checks whether this plug-in can load Texture in the specified file
   // based on its own criteria. Returns true if it can load the file and false 
   // otherwise.
   //---------------------------------------------------------------------------------
   virtual bool CanLoadTexture( RmTextureType textureType,
                                const RM_TCHAR *strFileName );

   //=======================================================================================//
   // Load Texture from the given file described by the specified file name                 //
   //=======================================================================================//
   virtual bool LoadTexture( const RM_TCHAR    *strFileName, 
                             RmTexture* pTexture,
                             RmPixelFormatType format = RM_PIXELFORMAT_UNKNOWN );

   //---------------------------------------------------------------------------------
   // This method is used to perform plug-in specific initialization/uninitialization
   //---------------------------------------------------------------------------------
   virtual bool Init(); 
   virtual void Uninitialize(); 

   //---------------------------------------------------------------------------------
   // This method is used by RenderMonkey to determine what type of the plug-in this
   // one is and what type of nodes it is supposed to be associated with. See 
   // Wizard/Include/Core/IRmPlugIn.h for more details.
   //---------------------------------------------------------------------------------
   virtual const RmPlugInDescription& GetPlugInDescription() const { return m_plugInDesc; };

   //---------------------------------------------------------------------------------
   // RenderMonkey main message handling entry point. RenderMonkey communicates
   // all of its events with the loaded plug-ins via messages. See 
   // Wizard/Include/Core/RmDefines.h for more details on each message.
   //---------------------------------------------------------------------------------
   virtual int MessageHandler(   int nMessageID,
                                 int nMessageData,
                                 int nMessageParameter = 0,
                                 const RmPlugInID* pRmPlugInID = NULL );

private:    // Data:

   // Plug-in description structure:
   RmPlugInDescription m_plugInDesc;
}; // End of CVTFLoaderPlugIn


#endif // End of _VTFLoader_PlugIn_H_
